#Read in Data

In [ ]:
import pandas as pd
x_train = pd.read_csv('X_train.csv')
x_test = pd.read_csv('X_val.csv')
y_train = pd.read_csv('y_train.csv')
y_test = pd.read_csv('y_val.csv')

#Model definitions

In [ ]:
#Installation
!pip install interpret -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 60.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 758.0/758.0 KB 57.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.7/275.7 KB 28.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 119.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 MB 110.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 111.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.4/572.4 KB 59.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 KB 16.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.1/246.1 KB 31.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 74.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.9/132.9 KB 19.6 MB/s eta 0:00:00


In [ ]:
from pandas.core.window.rolling import numba_notes
#Regression Models
from sklearn.linear_model import ElasticNet
from sklearn.ensemble import GradientBoostingRegressor as XGBRegressor
#Linear Regression 
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
#Ridge Regression 
from sklearn import linear_model
ridge = linear_model.Ridge(alpha=.99)
#Lasso Regression
from sklearn.linear_model import Lasso, LassoCV, LinearRegression
lasso = linear_model.Lasso(alpha=0.0)
#KNeighborsRegressor
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=3, weights='distance')
#Random Forrest
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(max_depth=30, max_features='auto', min_samples_leaf=4)
#Decision Trees
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor(max_depth=3, max_features='auto', min_samples_leaf=3, min_weight_fraction_leaf=0.2)
#SVM - SVR
from sklearn import svm
SVM = svm.SVR()
#Gradient Boosting Regressor
from sklearn.ensemble import GradientBoostingRegressor
gbr = GradientBoostingRegressor(learning_rate = 0.02, n_estimators = 80, random_state=0)
# XGBoost
import xgboost as xg
xgb = xg.XGBRegressor(learning_rate = 0.1, max_depth = 10, n_estimators = 100)
# EBM
from interpret import show
from interpret.data import Marginal
from interpret.glassbox import ExplainableBoostingRegressor, LinearRegression, RegressionTree
ebm = ExplainableBoostingRegressor(interactions=100)

In [ ]:
x_train

country  team  season  md  outcome  Cluster  win  goals        gd  \
0            4   154    2018  13        1        0    0    0.2  0.500000   
1            4   179    2010  19        1        0    0    0.1  0.500000   
2            2    31    2006   6        0        2    0    0.0  0.444444   
3            4    29    2013  18        2        2    1    0.1  0.555556   
4            1   170    2004  24        2        0    1    0.2  0.611111   
...        ...   ...     ...  ..      ...      ...  ...    ...       ...   
54752        2     2    2006   1        2        0    1    0.3  0.666667   
54753        3   157    2016  16        2        2    1    0.2  0.555556   
54754        4   142    2019  37        0        2    0    0.1  0.444444   
54755        2   189    2012  13        0        0    0    0.0  0.333333   
54756        1    28    2010  10        1        0    0    0.1  0.500000   

         opp_gd  avg_starter_age      win%  
0      0.500000         0.531856  0.076923  
1      0.500000         0.443609  0.105263  
2      0.555556         0.511278  0.500000  
3      0.444444         0.514170  0.888889  
4      0.388889         0.444976  0.375000  
...         ...              ...       ...  
54752  0.333333         0.506073  1.000000  
54753  0.444444         0.470588  0.562500  
54754  0.555556         0.561404  0.270270  
54755  0.666667         0.534413  0.307692  
54756  0.500000         0.614035  0.000000  

[54757 rows x 12 columns]

In [ ]:
y_train = y_train.values

In [ ]:
type(y_train)

numpy.ndarray

In [ ]:
y_train[0:2]

array([[0.04359431],
       [0.04537367]])

In [ ]:
y_train.values

array([[0.04359431],
       [0.04537367],
       [0.12279804],
       ...,
       [0.12597865],
       [0.06205516],
       [0.00907473]])

In [ ]:
x_train.values

array([[4.00000000e+00, 1.54000000e+02, 2.01800000e+03, ...,
        5.00000000e-01, 5.31855956e-01, 7.69230769e-02],
       [4.00000000e+00, 1.79000000e+02, 2.01000000e+03, ...,
        5.00000000e-01, 4.43609023e-01, 1.05263158e-01],
       [2.00000000e+00, 3.10000000e+01, 2.00600000e+03, ...,
        5.55555556e-01, 5.11278195e-01, 5.00000000e-01],
       ...,
       [4.00000000e+00, 1.42000000e+02, 2.01900000e+03, ...,
        5.55555556e-01, 5.61403509e-01, 2.70270270e-01],
       [2.00000000e+00, 1.89000000e+02, 2.01200000e+03, ...,
        6.66666667e-01, 5.34412955e-01, 3.07692308e-01],
       [1.00000000e+00, 2.80000000e+01, 2.01000000e+03, ...,
        5.00000000e-01, 6.14035088e-01, 0.00000000e+00]])

In [ ]:
type(x_train)

numpy.ndarray

In [ ]:
x_train[0:2]

array([[4.00000000e+00, 1.54000000e+02, 2.01800000e+03, 1.30000000e+01,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.00000000e-01,
        5.00000000e-01, 5.00000000e-01, 5.31855956e-01, 7.69230769e-02],
       [4.00000000e+00, 1.79000000e+02, 2.01000000e+03, 1.90000000e+01,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e-01,
        5.00000000e-01, 5.00000000e-01, 4.43609023e-01, 1.05263158e-01]])

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from math import sqrt
x_train_here = x_train.values
y_train_here = y_train.values
x_train_here

array([[4.00000000e+00, 1.54000000e+02, 2.01800000e+03, ...,
        5.00000000e-01, 5.31855956e-01, 7.69230769e-02],
       [4.00000000e+00, 1.79000000e+02, 2.01000000e+03, ...,
        5.00000000e-01, 4.43609023e-01, 1.05263158e-01],
       [2.00000000e+00, 3.10000000e+01, 2.00600000e+03, ...,
        5.55555556e-01, 5.11278195e-01, 5.00000000e-01],
       ...,
       [4.00000000e+00, 1.42000000e+02, 2.01900000e+03, ...,
        5.55555556e-01, 5.61403509e-01, 2.70270270e-01],
       [2.00000000e+00, 1.89000000e+02, 2.01200000e+03, ...,
        6.66666667e-01, 5.34412955e-01, 3.07692308e-01],
       [1.00000000e+00, 2.80000000e+01, 2.01000000e+03, ...,
        5.00000000e-01, 6.14035088e-01, 0.00000000e+00]])

In [ ]:
y_train_here

array([[0.04359431],
       [0.04537367],
       [0.12279804],
       ...,
       [0.12597865],
       [0.06205516],
       [0.00907473]])

In [ ]:
models = [lasso,  rf, dt, SVM, gbr, xgb, ebm] #lm, ridge, neigh
labels = ['Lasso', 'Random Forrest', 'Deision Tree', 'SVM', 'Gradient Boosting', 'XGBoost', 'EBM'] # 'Linear', 'Ridge', 'KNN'

In [ ]:
models

[Lasso(alpha=0.0),
 RandomForestRegressor(max_depth=30, max_features='auto', min_samples_leaf=4),
 DecisionTreeRegressor(max_depth=3, max_features='auto', min_samples_leaf=3,
                       min_weight_fraction_leaf=0.2),
 SVR(),
 GradientBoostingRegressor(learning_rate=0.02, n_estimators=80, random_state=0),
 XGBRegressor(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=10, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_paralle

In [ ]:
x_train_here.shape

(54757, 12)

In [ ]:
y_train_here.shape

(54757, 1)

In [ ]:
from mlxtend.regressor import StackingCVRegressor
stack = StackingCVRegressor(regressors=models,
                            meta_regressor=xg.XGBRegressor(n_estimators=60, max_depth = 3, learning_rate = 0.2), 
                            cv=10,
                            use_features_in_secondary=True,
                            store_train_meta_features=True,
                            shuffle=False
                           )

In [ ]:
stack.fit(x_train_here, y_train_here)
pred = stack.predict(x_test)
score_mae = mean_absolute_error(y_test, pred)
score_mse = mean_squared_error(y_test, pred)
score_r2=r2_score(y_test, pred)*100
score_rmse =  sqrt(score_mse)
print('Model: {0}, MAE: {1}'.format(type(stack).__name__, score_mae))
print('Model: {0}, MSE: {1}'.format(type(stack).__name__, score_mse))
print('Model: {0}, RMSE: {1}'.format(type(stack).__name__, score_rmse))
print('Model: {0}, R2: {1}'.format(type(stack).__name__, score_r2))

/usr/local/lib/python3.9/dist-packages/mlxtend/regressor/stacking_cv_regression.py:180: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  instance.fit(X[train_idx], y[train_idx])
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.277e+02, tolerance: 5.455e-02 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet

Model: StackingCVRegressor, MAE: 0.011308244385590485
Model: StackingCVRegressor, MSE: 0.00036526766097287
Model: StackingCVRegressor, RMSE: 0.01911197689860654
Model: StackingCVRegressor, R2: 96.4251398940928


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but GradientBoostingRegressor was fitted without feature names
  warnings.warn(


In [ ]:
stacking_results = []
stacking_results.append({'Model': 'Stacked Model', 'Mean Absolute Error': score_mae, 'Mean Squared Error': score_mse, 'RMSE': score_rmse,'R-squared': score_r2})

df = pd.DataFrame(stacking_results)
df

Model  Mean Absolute Error  Mean Squared Error      RMSE  R-squared
0  Stacked Model             0.011308            0.000365  0.019112   96.42514